
import javax.swing.JFrame;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmHockeyMatch.java
 *
 * Created on Jan 14, 2016, 11:16:46 AM
 */
/**
 *
 * @author Administrator
 */
public class FrmHockeyMatch extends javax.swing.JFrame {

    /** Creates new form FrmHockeyMatch */
    public FrmHockeyMatch() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTeam = new javax.swing.JMenu();
        mnuManage = new javax.swing.JMenuItem();
        mnuCompetition = new javax.swing.JMenu();
        mnuStart = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ILVA Inter School Hockey Match");

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 56));
        jLabel1.setText("ILVA Inter School Hockey Match");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hockey.jpg"))); // NOI18N

        mnuTeam.setText("Team");
        mnuTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTeamActionPerformed(evt);
            }
        });

        mnuManage.setText("Manage");
        mnuManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageActionPerformed(evt);
            }
        });
        mnuTeam.add(mnuManage);

        jMenuBar1.add(mnuTeam);

        mnuCompetition.setText("Competition");
        mnuCompetition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCompetitionActionPerformed(evt);
            }
        });

        mnuStart.setText("Start");
        mnuStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStartActionPerformed(evt);
            }
        });
        mnuCompetition.add(mnuStart);

        jMenuBar1.add(mnuCompetition);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel2)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(816, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnuTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTeamActionPerformed

}//GEN-LAST:event_mnuTeamActionPerformed

private void mnuCompetitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCompetitionActionPerformed
    
}//GEN-LAST:event_mnuCompetitionActionPerformed

private void mnuManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageActionPerformed
    FrmTeamMaster frm = new FrmTeamMaster();
    frm.show();
}//GEN-LAST:event_mnuManageActionPerformed

private void mnuStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStartActionPerformed
    FrmMatch frm = new FrmMatch();
    frm.show();
}//GEN-LAST:event_mnuStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHockeyMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHockeyMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHockeyMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHockeyMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmHockeyMatch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuCompetition;
    private javax.swing.JMenuItem mnuManage;
    private javax.swing.JMenuItem mnuStart;
    private javax.swing.JMenu mnuTeam;
    // End of variables declaration//GEN-END:variables
}
