
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMatch.java
 *
 * Created on Jan 5, 2016, 11:06:30 AM
 */
/**
 *
 * @author Administrator
 */
public class FrmMatch extends javax.swing.JFrame {

    Object[] TeamId;

    /** Creates new form FrmMatch */
    public FrmMatch() {
        initComponents();
        FillTeam();
    }

    void FillTeam() {
        try {
            int i = 0;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/HockeyMatchDB", "root", "root");
            String sql = "Select count(TeamId) from TeamMaster where WinningStatus = 1";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int cnt = Integer.parseInt(rs.getString(1));
                if (cnt == 1) {
                    sql = "Select * from TeamMaster where WinningStatus = 1";
                    ps = con.prepareStatement(sql);
                    rs = ps.executeQuery();
                    if(rs.next())
                        JOptionPane.showMessageDialog(this, "Winning Team is " + rs.getString("TeamName"));
                } 
                else {
                    TeamId = new Object[cnt];
                    sql = "Select * from TeamMaster where WinningStatus = 1";
                    ps = con.prepareStatement(sql);
                    rs = ps.executeQuery();
                    i = 0;
                    while (rs.next()) {
                        cmbTeam1.addItem(rs.getString("TeamName"));
                        cmbTeam2.addItem(rs.getString("TeamName"));
                        TeamId[i] = rs.getString("Teamid");
                        i++;
                    }
                    cmbTeam1.setSelectedIndex(-1);
                    cmbTeam2.setSelectedIndex(-1);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        btnSave2 = new javax.swing.JButton();
        btnSave3 = new javax.swing.JButton();
        cmbTeam1 = new javax.swing.JComboBox();
        cmbTeam2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hockey Match");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel4.setText("Goal By");

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 12));
        btnSave.setText("Submit");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txt2.setText("0");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("Match Master");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel2.setText("Team 1");

        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 12));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3.setText("Team 2");

        txt1.setText("0");

        btnSave2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        btnSave2.setText("Team 1");
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        btnSave3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        btnSave3.setText("Team 2");
        btnSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave3ActionPerformed(evt);
            }
        });

        cmbTeam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTeam1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(cmbTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(cmbTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(btnSave2)
                        .addGap(6, 6, 6)
                        .addComponent(btnSave3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnSave)
                        .addGap(6, 6, 6)
                        .addComponent(btnClose)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(cmbTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(cmbTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addComponent(btnSave2)
                    .addComponent(btnSave3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    try {
        int a, b;
        a = Integer.parseInt(txt1.getText());
        b = Integer.parseInt(txt2.getText());
        if (a == b) {
            JOptionPane.showMessageDialog(this, "Match Tie Extra Time Given");
        } else {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/HockeyMatchDB", "root", "root");
            String sql = "Insert into MatchMaster(TeamId1,TeamId2,WinningTeamId) values(?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, TeamId[cmbTeam1.getSelectedIndex()].toString());
            ps.setString(2, TeamId[cmbTeam2.getSelectedIndex()].toString());
            if (a > b) {
                ps.setString(3, TeamId[cmbTeam1.getSelectedIndex()].toString());
                PreparedStatement ups = con.prepareStatement("Update TeamMaster set WinningStatus=0 where TeamId=" + TeamId[cmbTeam2.getSelectedIndex()]);
                ups.executeUpdate();
                JOptionPane.showMessageDialog(this, "Winning Team is " + cmbTeam1.getSelectedItem());
            } else {
                ps.setString(3, TeamId[cmbTeam2.getSelectedIndex()].toString());
                PreparedStatement ups = con.prepareStatement("Update TeamMaster set WinningStatus=0 where TeamId=" + TeamId[cmbTeam1.getSelectedIndex()]);
                ups.executeUpdate();
                JOptionPane.showMessageDialog(this, "Winning Team is " + cmbTeam2.getSelectedItem());
            }
            int rs = ps.executeUpdate();
            if (rs == 1) {
                JOptionPane.showMessageDialog(this, "Match Result Saved");
                cmbTeam1.setSelectedIndex(-1);
                cmbTeam2.setSelectedIndex(-1);
                txt1.setText("");
                txt2.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Not Saved");
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_btnSaveActionPerformed

private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    this.dispose();
}//GEN-LAST:event_btnCloseActionPerformed

private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
    
}//GEN-LAST:event_btnSave2ActionPerformed

private void btnSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave3ActionPerformed
    
}//GEN-LAST:event_btnSave3ActionPerformed

private void cmbTeam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTeam1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbTeam1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmMatch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnSave3;
    private javax.swing.JComboBox cmbTeam1;
    private javax.swing.JComboBox cmbTeam2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
